### ISSUE TITLE
Add documentation search to the OSS site

### ISSUE THREAD

**Issue by simonplend** [platformatic/oss#29]
A search feature will make it much easier for users to navigate the documentation and find the information they need.

I'd suggest setting up [Algolia DocSearch](https://docsearch.algolia.com/) (free for any open-source project) with Docusaurus: https://docusaurus.io/docs/search#using-algolia-docsearch

**Comment by leorossi** [comment]
Just requested our spot and waiting response from them 🤞

**Comment by HassanBahati** [comment]
> Just requested our spot and waiting response from them crossed_fingers

@leorossi am quite curious to know if we have yet gotten a response...

**Comment by HassanBahati** [comment]
@simonplend @leorossi issue #51 by @mcollina suggests that we implement `Lyra Search`. Would this mean we are dropping the option of `Algolia` ?

**Comment by simonplend** [comment]
The OSS documentation site would really benefit from having a search feature. If we haven't yet heard back from Algolia I think it makes sense to go ahead and implement Lyra for search.

**Comment by leorossi** [comment]
Aloglia need an approval for them that never arrived so far. I guess we can drop it and give Lyra a chance

**Comment by HassanBahati** [comment]
this is noted
