### ISSUE TITLE
Add Lyra for search

### ISSUE THREAD

**Issue by mcollina** [platformatic/oss#51]
https://www.npmjs.com/package/@lyrasearch/plugin-docusaurus should provide a nice search system for us.

Guide to integrating Lyra with Docusaurus: https://docs.lyrasearch.io/plugins/docusaurus-plugin/

**Comment by imrishabh18** [comment]
@mcollina Can you provide more information regarding this issue please? I would like to contribute

**Comment by mcollina** [comment]
Follow the instructions in the plugin README -I guess, it should be used to implement search.

**Comment by simonplend** [comment]
@imrishabh18 Hey Rishabh, let me know if you need any help with this. I'm also hanging out on the Platformatic Discord if it's easier to chat there.

**Comment by imrishabh18** [comment]
@simonplend I was trying to integrate `Lyra` but the thing I am getting stuck at is, when I have installed the plugin it is causing some issues with the `@theme/layout` package and shows some error. 

And, as we are using webpack for building this docs, to see my reflected changes it is taking a lot of time, it seems to be very slow, I mean literally very slow.

**Comment by imrishabh18** [comment]
@simonplend Yes, I am using that guide.

Okay, will make a draft PR with the error messages and share.

**Comment by mcollina** [comment]
Done in #70
