### ISSUE TITLE
Add Contributing Guide

### ISSUE THREAD

**Issue by HassanBahati** [platformatic/oss#55]
I have had a rough ride trying to get this project up and running and this has motivated me to open this issue in a bid to smoother for 1st time contributors to get started.

I am available to support and contribute to this!

**Comment by HassanBahati** [comment]
In [README.md](https://github.com/platformatic/oss/blob/main/README.md), the guide on how to get started is as below
```md
There are two ways to do this

    run ./scripts/doc-watcher.js --source ../relative/path/to/plt/docs/directory in one terminal and run npx docusaurus start on another
    run DOCS=path/to/platformatic/docs npm run start.

```

i have tried running the above the above commands but its not quite clear if the `path` should point to a `docs` directory which is inexistent or should point to `versioned_docs` directory.

here is a screenshot of the results i have been getting as i tried running the above.
![Screenshot from 2023-01-30 02-41-34](https://user-images.githubusercontent.com/65954740/215362688-2380db5c-6867-4667-bfaf-92320978fe05.png)

I think we should also include a clause that guides 1st time contributors no how to go about this.
cc: @mcollina @leorossi

**Comment by HassanBahati** [comment]
@leorossi please guide on how to go about setting up and running the project

**Comment by leorossi** [comment]
I'd choose the cleaner `run DOCS=path/to/platformatic/docs npm run start`

I see you are pointing to `oss/docs` directory, but you should point to [this](https://github.com/platformatic/platformatic/tree/main/docs) directory instead.

**Comment by mcollina** [comment]
I think a `CONTRIBUTING.md` guide should be clearer than what we have in the README. While it's clear from our point of view, it might be disorienting for a newbie. Instead of saying:

> Documentation lives in [Platformatic DB](https://github.com/platformatic/platformatic/tree/main/docs) repo.

We must say:

1. Clone `https://github.com/platformatic/platformatic` in a folder of your choosing; in the following example, we will use `/path/to/platformatic`.
2. Run `DOCS=/path/to/platformatic/docs npm run start`

@HassanBahati could you verify if the above work, and in case, create a `CONTRIBUTING.md` from a newbie perspective?

**Comment by HassanBahati** [comment]
@leorossi tried pointing to [this](https://github.com/platformatic/platformatic/tree/main/docs) directory and results in an error
![Screenshot from 2023-02-02 14-43-21](https://user-images.githubusercontent.com/65954740/216316171-0794ed55-37db-479d-aab0-e3f5c1a9981e.png)

**Comment by HassanBahati** [comment]
@leorossi tried pointing to [this](https://github.com/platformatic/platformatic/tree/main/docs) and results in an error
![Screenshot from 2023-02-02 14-43-21](https://user-images.githubusercontent.com/65954740/216316641-5c8ac8f5-84a4-4875-93c0-54f5b6a67463.png)

**Comment by mcollina** [comment]
I've added step-by-step instructions in https://github.com/platformatic/oss/pull/56.

You can read more about cloning a repository at https://git-scm.com/book/en/v2/Git-Basics-Getting-a-Git-Repository. I would also recommend you to familiarize yourself with git with https://gitimmersion.com/.
